//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _DISTANCETOGOALSERVICEINHANDLER_HH
#define _DISTANCETOGOALSERVICEINHANDLER_HH

#include "DistanceToGoalServiceInHandlerCore.hh"
#include <RoqmeWriterImpl.h>
	
class DistanceToGoalServiceInHandler  : public DistanceToGoalServiceInHandlerCore
{		
public:
	DistanceToGoalServiceInHandler(Smart::InputSubject<CommNavigationObjects::DistanceToGoal> *subject, const int &prescaleFactor=1);
	virtual ~DistanceToGoalServiceInHandler();
	
	virtual void on_DistanceToGoalServiceIn(const CommNavigationObjects::DistanceToGoal &input);

private:
	Roqme::RoqmeDoubleWriter distanceWriter;
	double previous_value;
};

#endif
