//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _PAYLOADSERVICEINHANDLER_HH
#define _PAYLOADSERVICEINHANDLER_HH

#include "PayloadServiceInHandlerCore.hh"
#include <RoqmeWriterImpl.h>
#ifdef ROQME_DEBUG
#include <RoqmeDebug.h>
#endif
	
class PayloadServiceInHandler  : public PayloadServiceInHandlerCore
{		
public:
	PayloadServiceInHandler(Smart::InputSubject<CommBasicObjects::RobotPayload> *subject, const int &prescaleFactor=1);
	virtual ~PayloadServiceInHandler();
	
	virtual void on_PayloadServiceIn(const CommBasicObjects::RobotPayload &input);

private:
	Roqme::RoqmeEnumWriter available_space_dw;
	Roqme::RoqmeEnumWriter payload_weight_dw;
#ifdef ROQME_DEBUG
	Roqme::RoqmeDebug roqmeOut;
#endif
	std::string prev_available;
	std::string prev_payload;
	const double MAX_MASS = 5.0;
	const unsigned int MAX_ITEMS = 3;

};

#endif
