//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _PEOPLEPUSHSERVICEINHANDLER_HH
#define _PEOPLEPUSHSERVICEINHANDLER_HH

#include "PeoplePushServiceInHandlerCore.hh"
#include <RoqmeWriterImpl.h>
#ifdef ROQME_DEBUG
#include <RoqmeDebug.h>
#endif
	
class PeoplePushServiceInHandler  : public PeoplePushServiceInHandlerCore
{		
public:
	PeoplePushServiceInHandler(Smart::InputSubject<CommObjectRecognitionObjects::CommPeople> *subject, const int &prescaleFactor=1);
	virtual ~PeoplePushServiceInHandler();
	
	virtual void on_PeoplePushServiceIn(const CommObjectRecognitionObjects::CommPeople &input);
private:
	Roqme::RoqmeEnumWriter peopleWriter;
#ifdef ROQME_DEBUG
	Roqme::RoqmeDebug roqmeOut;
#endif
	std::string prev_value;
};

#endif
