//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "BaseStateQueryHandler.hh"
#include "ComponentWebotsRobot.hh"

BaseStateQueryHandler::BaseStateQueryHandler(IQueryServer *server)
:	BaseStateQueryHandlerCore(server)
{
	
}


void BaseStateQueryHandler::handleQuery(const Smart::QueryIdPtr &id, const CommBasicObjects::CommVoid& request) 
{
	CommBasicObjects::CommBaseState commCurrentBaseState;
	if (COMP->_pose != NULL) {
		commCurrentBaseState.set_base_position(COMP->_pose->getBasePose());
		commCurrentBaseState.set_base_raw_position(COMP->_pose->getBasePose());
	}
	else {
		std::cout << "Webots Simulator not yet started !" << std::endl;
	}
	CommBasicObjects::CommTimeStamp time_stamp;
	time_stamp.set_now();
	commCurrentBaseState.set_time_stamp(time_stamp);

    this->server->answer(id, commCurrentBaseState);
}
