//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _LIDARTASK_HH
#define _LIDARTASK_HH

#include "LidarTaskCore.hh"

#include "CommBasicObjects/CommMobileLaserScan.hh"

#include "webots/Lidar.hpp"

class LidarTask  : public LidarTaskCore
{
private:
	int horizontalResolution;
  	unsigned int numberValidPoints;
	double field_of_view;
	
	webots::Lidar* _lidar;
	CommBasicObjects::CommMobileLaserScan scan;
	unsigned long scanCount;
	double bumper_threshold_;
	CommBasicObjects::BumperEventType bumper_type_;
	int computeLidarUpdate() const;
public:
	bool firstExecution;

	LidarTask(SmartACE::SmartComponent *comp);
	virtual ~LidarTask();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
