//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "PeopleEventServiceOutEventTestHandler.hh"

bool PeopleEventServiceOutEventTestHandler::testEvent(
	CommBasicObjects::CommVoid &p,
	CommObjectRecognitionObjects::CommObjectRecognitionEventResult &r,
	const CommObjectRecognitionObjects::CommObjectRecognitionEventState &s
) throw() {
		if (s.get_state() == CommObjectRecognitionObjects::ObjectRecognitionState::VISIBLE)
			r.setObject_id(s.getObject_idCopy());
		r.set_state(r.get_state());
	return true;
}
