//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "PeopleQueryServiceAnswHandler.hh"
#include "ComponentWebotsPersonRecognition.hh"

PeopleQueryServiceAnswHandler::PeopleQueryServiceAnswHandler(IQueryServer *server)
:	PeopleQueryServiceAnswHandlerCore(server)
{
	_people.setIs_valid(false);
}

void PeopleQueryServiceAnswHandler::on_update_from(const RecognitionTask* recognitionTask)
{
	// update triggered from RecognitionTask
	// (use a local mutex here, because this method is called from within the thread of RecognitionTask)
	mutex.acquire();

	_people = recognitionTask->_comm_people;

	mutex.release();
}

void PeopleQueryServiceAnswHandler::handleQuery(const Smart::QueryIdPtr &id, const CommBasicObjects::CommVoid& request) 
{
	this->server->answer(id, _people);
}
