//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "ObjectPlacementQueryServiceAnswHandler.hh"
#include "ComponentWebotsHRI.hh"

ObjectPlacementQueryServiceAnswHandler::ObjectPlacementQueryServiceAnswHandler(IQueryServer *server)
:	ObjectPlacementQueryServiceAnswHandlerCore(server)
{
	
}

void ObjectPlacementQueryServiceAnswHandler::on_update_from(const SpeechTask* speechTask)
{
	// update triggered from SpeechTask
	// (use a local mutex here, because this method is called from within the thread of SpeechTask)
}

void ObjectPlacementQueryServiceAnswHandler::handleQuery(const Smart::QueryIdPtr &id, const DomainSpeech::CommObjectPlacementOutputMessage& request) 
{
	CommBasicObjects::CommBool answer;
	
	// implement your query handling logic here and fill in the answer object
	
	this->server->answer(id, answer);
}
