//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "ObjectDropQueryServiceAnswHandler.hh"
#include "ComponentWebotsHRI.hh"

ObjectDropQueryServiceAnswHandler::ObjectDropQueryServiceAnswHandler(IQueryServer *server)
:	ObjectDropQueryServiceAnswHandlerCore(server)
{
	
}

void ObjectDropQueryServiceAnswHandler::on_update_from(const SpeechTask* speechTask)
{}

void ObjectDropQueryServiceAnswHandler::handleQuery(const Smart::QueryIdPtr &id, const DomainSpeech::CommObjectDropOutputMessage& request) 
{
	COMP->obj_drop_msg = request;
	CommBasicObjects::CommBool answer;
	answer.setBoolValue(true);
	this->server->answer(id, answer);
}
